spring:
  profile:
    active: native
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          clone-on-start: true
          default-label: master
          uri: https://github.com/Cristianaaguirre/configuration

server:
  port: 8888
