spring:
  profile:
    active: native
  application:
    name: configserver
  cloud:
    config:
      enabled: true
      server:
        git:
          clone-on-start: true
          default-label: master
          uri: https://github.com/Cristianaaguirre/configuration

server:
  port: 8888
