server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    config:
      enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: students
          uri : http://localhost:9999
          predicates:
            - Path=/api/student/**
        - id: courses
          uri: http://localhost:9898
          predicate:
            - Path=/api/course/**