spring:
  profile:
    active: native
  application:
    name: configserver
  cloud:
    config:
      enabled: true
      server:
        git:
          uri: /home/ubuntu/Escritorio/git-configurations/configuration

server:
  port: 8888
