server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    config:
      enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: mvs-student
          uri : http://localhost:9999
          predicates:
            - Path=/api/student/**
        - id: msvc-course
          uri: http://localhost:9898
          predicates:
            - Path=/api/course/**