server:
  port: 9898

spring:
  application:
    name: msvc-course
  datasource:
    url: jdbc:postgresql://localhost:5433/course
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  config:
    import:
      - optional:configserver:http://localhost:8888/